# Generated by Django 4.1.1 on 2023-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pelelangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=75)),
                ("lintang", models.FloatField(null=True)),
                ("bujur", models.FloatField(null=True)),
                ("deskripsi", models.CharField(max_length=150)),
            ],
        ),
    ]
