# Generated by Django 4.1.1 on 2023-01-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikan_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ikan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_Ikan", models.CharField(max_length=75)),
                ("harga", models.CharField(max_length=50)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
