# Generated by Django 4.1.1 on 2023-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikan_app", "0002_ikan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelelangan",
            name="deskripsi",
            field=models.CharField(max_length=750),
        ),
    ]
