# Generated by Django 4.1.1 on 2023-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ikan_app", "0003_alter_pelelangan_deskripsi"),
    ]

    operations = [
        migrations.RemoveField(model_name="pelelangan", name="deskripsi",),
    ]
